### ISSUE TITLE
Support access via Proxy

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/ansible-nae#33]
If a proxy is in the middle (tested with Cisco dCloud access) the login will fail. 
I this is is because we are not saving the "SRVNAME" Cookie inserted by the proxy.
As a consequence the proxy will then not recognise the session and strip all the custom cookies like the OTP one as we can see in #32

**Comment by lhercot** [comment]
Closing this issue as we have now officially released the PCV support for the ND Ansible Collection. The NAE Collection is deprecated.
