### ISSUE TITLE
Nae_compliance: ability to activate/disactivate requirement_set (Expose 'active' attribute as parameter)

### ISSUE THREAD

**Issue by itommasi** [CiscoDevNet/ansible-nae#36]
When you now play nae_compliance for a new requirement_set, it activates it by default on the AG and there is no possibility to only configure the set without activating it.

Since you can only have 3 sets active at the same time, it would be handy to just configure your set without activating it.

The module supported parameters are: ag_name, description, form, host, name, password, port, selector, state, username, validate_certs".

The form only contains the name and the list of requirements

{
          "name": "Segmentation_Set",
          "requirements": [
              "Segmentation_req1", 
              "Segmentation_req2"
          ]
        }

Thanks!

**Comment by lhercot** [comment]
@itommasi I think we merged this change this week and @xinyuezhao is in the process of releasing the new NAE version which contains it. See https://github.com/CiscoDevNet/ansible-nae/blob/5347d3ee9b0fee5c4bf2a304948f30d6eff36d6f/plugins/modules/nae_compliance.py#L105

If you want to test it, you can use this update process: https://github.com/CiscoDevNet/ansible-mso#update
Just replace all the mso mentions by NAE. We should add this to the README here too.

We might need to update the documentation of the module though as I can't find those argument. @xinyuezhao do you know where the doc is for the active parameter?

**Comment by camrossi** [comment]
@lhercot we actually have the update process documented here already ;) 
https://github.com/CiscoDevNet/ansible-nae#testing-latest-code

**Comment by xinyuezhao** [comment]
hi @itommasi 
the new version v1.0.0 is released in galaxy and you can install the new version by this command:

ansible-galaxy collection install cisco.nae

@lhercot As for the documentation for those arguments, I suppose we need to update it.

**Comment by itommasi** [comment]
Thank you! Just installed the new collection and tested successfully. Issue/enhancement is resolved to me.
