### ISSUE TITLE
Documentation Issue: nae_prechange

### ISSUE THREAD

**Issue by 020003** [CiscoDevNet/ansible-nae#42]
Hi, 

seems like I found an Issue in the documentation of the nae_prechange module.

![image](https://user-images.githubusercontent.com/66415321/102087779-53be8a00-3e1a-11eb-9366-47494f81ae93.png)

The query NAE prechange explanation is in there twice and on the first occurrence it is stated that the state should be "verify"

**Comment by anvitha-jain** [comment]
Hi @020003 ,

The documentation issue is [addressed with this recent changes](https://github.com/CiscoDevNet/ansible-nae/blob/29276e97ea37abe28cacaf13e745c057679d8bb9/plugins/modules/nae_prechange.py#L145) made to the code. Use the newer version which will be released in few days.
