### ISSUE TITLE
nae_prechange fails on query state

### ISSUE THREAD

**Issue by 020003** [CiscoDevNet/ansible-nae#43]
Hi, 

I got a working playbook to create and query the nae prechange analysis. 
The query is working until the pre change analysis is done and when it gets the status "completed" the query is failing with following module error.

"Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1607952875.8573136-10584-170220307643012/AnsiballZ_nae_prechange.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1607952875.8573136-10584-170220307643012/AnsiballZ_nae_prechange.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1607952875.8573136-10584-170220307643012/AnsiballZ_nae_prechange.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nae.plugins.modules.nae_prechange', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_88bf6y31/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 215, in <module>\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_88bf6y31/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 198, in main\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_88bf6y31/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/module_utils/nae.py\", line 469, in get_pre_change_result\nTypeError: argument of type 'NoneType' is not iterable\n",

The playbook looks as following.

` - name: Play 1 Check Epoch Delta
  hosts: all
  connection: local

  tasks:
  
    - name: Query Prechange analysis
      cisco.nae.nae_prechange:
        host: "{{ nae }}"
        port: 443
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        ag_name: "{{ agName }}"
        name: NAEAnalysis
        state: query
      delegate_to: localhost
`

Please advice if I am holding it wrong :)

**Comment by anvitha-jain** [comment]
@020003
The above issue is addressed in this recent update and will be available in the new release in a few days. [As those changes ](https://github.com/CiscoDevNet/ansible-nae/blob/29276e97ea37abe28cacaf13e745c057679d8bb9/tests/integration/targets/nae_prechange/tasks/manual_upload.yml#L225) fulfill your request, I will close this issue.
Feel free to open a new issue in case you need any other enhancement.
