### ISSUE TITLE
Allow NAE Automation via Nexus Dashboard

### ISSUE THREAD

**Issue by 020003** [CiscoDevNet/ansible-nae#48]
Hi,

since Nexus Dashboard has been released api requests destined for NAE are going through the API gateway of Nexus Dashboard it's not using the ND login so far but all tasks are failing with module errors.
Please include support for NAE deployed on Nexus Dashboard. :)

**Comment by camrossi** [comment]
Hi Stephan,

I have NAE 5.1 installed on ND 2.0 and it works perfectly fine with the latest code. 
Can you let me know what error you are getting?

**Comment by 020003** [comment]
Hi Camillo,

maybe I am holding it wrong :) but on a virtual NAE its running without any issue.
`{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nae.plugins.modules.nae_prechange', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 266, in <module>\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 242, in main\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/module_utils/nae.py\", line 722, in create_pre_change_from_file\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/module_utils/nae.py\", line 1033, in send_pre_change_payload\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 2185, in fail_json\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 2157, in _return_formatted\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 426, in remove_values\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 403, in _remove_values_conditions\nTypeError: Value of unknown type: <class '_io.TextIOWrapper'>, <_io.TextIOWrapper name='/tmp/dump.json' mode='w' encoding='UTF-8'>\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1610609491.2876794-1557100-94607915530511/AnsiballZ_nae_prechange.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nae.plugins.modules.nae_prechange', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 266, in <module>\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/modules/nae_prechange.py\", line 242, in main\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/module_utils/nae.py\", line 722, in create_pre_change_from_file\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible_collections/cisco/nae/plugins/module_utils/nae.py\", line 1033, in send_pre_change_payload\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 2185, in fail_json\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 2157, in _return_formatted\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 426, in remove_values\n  File \"/tmp/ansible_cisco.nae.nae_prechange_payload_s36s9qvw/ansible_cisco.nae.nae_prechange_payload.zip/ansible/module_utils/basic.py\", line 403, in _remove_values_conditions\nTypeError: Value of unknown type: <class '_io.TextIOWrapper'>, <_io.TextIOWrapper name='/tmp/dump.json' mode='w' encoding='UTF-8'>\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {}
}`

Playbook looks as following.

`
- name: Play 1 Create PCA
  hosts: all
  connection: local


  tasks:
  
    - name: Add a new pre-change analysis from file
      cisco.nae.nae_prechange:
        host: "{{ nae }}"
        port: 443
        username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        ag_name: "{{ agName }}"
        file: /tmp/dump.json
        name: "{{ tenant_name }}"
        state: present
        verify: True
      delegate_to: localhost
`

**Comment by camrossi** [comment]
Just tried and it works fine on my system, did you install the latest collection with 
https://github.com/CiscoDevNet/ansible-nae#testing-latest-code ?

I am asking as you have some errors like:
`nae_prechange.py , line 266 ` and there is not line 266 in that file. 

Let me know

```
- name: Add a pre-change analysis from manual changes
  cisco.nae.nae_prechange:
    <<: *nae_login
    ag_name: Change Management
    name: PreChangeVerification2
    state: present
    file: /Users/camrossi/Downloads/BD-test.json
  tags:
    - nae_pcv1

ansible-playbook  -i inventory.yaml main.yml --tags="nae_pcv1" -vvv

=== SNIP ===
changed: [10.67.185.6] => {
    "Result": "Pre-change analysis PreChangeVerification2 successfully created.",
    "changed": true,
    "invocation": {
        "module_args": {
            "action": "RUN",
            "ag_name": "Change Management",
            "base_epoch_id": "5597aa81-a1f914cf-1ae4-3db2-8b51-1207d9f450b5",
            "changes": [],
            "description": null,
            "fabric_id": "5597aa81-b3d2ad60-eb52-4f74-886f-956d7c9798d1",
            "file": "/Users/camrossi/Downloads/BD-test.json",
            "host": "10.67.185.6",
            "ignore_sm": [],
            "name": "PreChangeVerification2",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "save": false,
            "state": "present",
            "username": "admin",
            "validate_certs": false,
            "verify": false
```

**Comment by 020003** [comment]
My tower is installing the latest Version based on the requirements.yml.
At the moment its 1.0.1

"/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\b\\\b|\b/\b-\bInstalling 'cisco.nae:1.0.1' to '/var/lib/awx/projects/.__awx_cache/_9__automation/stage/requirements_collections/ansible_collections/cisco/nae'",


I will check later how that file looks like

**Comment by 020003** [comment]
Typo issue ....
