### ISSUE TITLE
Start/Stop Assurance Groups 

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/ansible-nae#51]
We should add to the AG Module to capability to start/stop an online analysis. 

We should support these 3 use cases:
- Start 
- Run X times 
- Stop 

Note: This is a customer request

**Comment by lhercot** [comment]
Run X times can be done with a loop or a playbook right?

**Comment by camrossi** [comment]
There is a specific option for it in the GUI to say run X rimes, we should support the same probably
