### ISSUE TITLE
nae_prechange: Verify Documentation is wrong 

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/ansible-nae#53]
https://github.com/CiscoDevNet/ansible-nae/blob/master/plugins/modules/nae_prechange.py#L40

Verify Is either `true` or `false` the doc speaks of `present` and `query` this needs to be fixed

**Comment by lhercot** [comment]
The doc is correct. I don't think it need to be changed.

**Comment by camrossi** [comment]
I understand what you mean but I think we can be a bit more clearer. I will send in a proposal later on to make it more obvious
