### ISSUE TITLE
Add support for remote AAA domains

### ISSUE THREAD

**Issue by aism** [CiscoDevNet/ansible-nae#59]
Hello,

Please add the support for non-Local AAA domains.
Currently only Local is supported as a AAA domain (hardcoded in nae.py).

Also, would be worth to mention the fact that currently only Local is supported in the docs for the module.

**Comment by lhercot** [comment]
Closing this issue as we have now officially released the PCV support for the ND Ansible Collection and it supports AAA domains by default. The NAE Collection is deprecated.
