### ISSUE TITLE
No public-facing docs available for NAE collection

### ISSUE THREAD

**Issue by aism** [CiscoDevNet/ansible-nae#60]
There's no public-facing docs available for this collection on galaxy site: https://docs.ansible.com/ansible/latest/collections/cisco/index.html

Workaround: use command line to view the built-in documentation for the module, for example `ansible-doc cisco.nae.nae_prechange`

**Comment by lhercot** [comment]
Closing this issue as we have now officially released the PCV support for the ND Ansible Collection. The NAE Collection is deprecated.
