### ISSUE TITLE
Please add abillity to create an PCA on NI 6.0

### ISSUE THREAD

**Issue by 020003** [CiscoDevNet/ansible-nae#62]
Hi, 

could you please add the ability to do also a PCA on NI 6.0?

**Comment by 416C6578** [comment]
Highly agreed

**Comment by lhercot** [comment]
The support of automation of PCV for Nexus Dashboard Insights 6.0 is on our roadmap but will not be added to this collection.

We are still deciding if it will be part of the ansible-nd collection or if we will be creating a new ansible-ndi collection.

**Comment by saurabhkothari** [comment]
Hello, 
Is there any alternative to using Ansible to PCA on NI 6.0? Python/REST ? I couldn't find a REST API guide for it. 

Thanks,

**Comment by lhercot** [comment]
The release of the ND Ansible collection v0.2.0 include  the cisco.nd.nd_pcv module which allow the creation of PCV in NI 6.0+.

See more details:
- https://galaxy.ansible.com/cisco/nd
- https://github.com/CiscoDevNet/ansible-nd/releases/tag/v0.2.0
